In [11]:
import pandas as pd
import seaborn as sns
import numpy as np

In [12]:
P_records=pd.read_csv('patient_records.csv')
P_records.head(2)

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
0,PT100000,Sarah,Jackson,Male,0,O+,CA,Former,Private,Type 2 Diabetes,152.3,81.8,71,58,75,2024-07-19
1,PT100001,Jessica,Smith,Female,53,O+,PA,Former,Medicaid,Anxiety Disorder,183.2,45.6,114,89,75,2025-01-16


In [13]:
P_records['primary_condition'].value_counts()

primary_condition
Hypertension               177
Type 2 Diabetes            170
Obesity                    132
Depression                 124
Anxiety Disorder            94
Coronary Artery Disease     93
Asthma                      90
Osteoarthritis              62
COPD                        52
Atrial Fibrillation         51
Hypothyroidism              51
Chronic Kidney Disease      42
GERD                        30
Migraine                    27
Name: count, dtype: int64

###  applying One-Hot Encoding in Pandas

In [14]:
P_records_HE=pd.get_dummies(P_records, columns=['primary_condition', 'blood_type'])
P_records_HE

,patient_id,first_name,last_name,gender,age,state,smoking_status,insurance_type,height_cm,weight_kg,...,primary_condition_Osteoarthritis,primary_condition_Type 2 Diabetes,blood_type_A+,blood_type_A-,blood_type_AB+,blood_type_AB-,blood_type_B+,blood_type_B-,blood_type_O+,blood_type_O-
0,PT100000,Sarah,Jackson,Male,0,CA,Former,Private,152.3,81.8,...,False,True,False,False,False,False,False,False,True,False
1,PT100001,Jessica,Smith,Female,53,PA,Former,Medicaid,183.2,45.6,...,False,False,False,False,False,False,False,False,True,False
2,PT100002,John,Nguyen,Male,70,PA,Never,Private,178.1,66.5,...,False,False,True,False,False,False,False,False,False,False
3,PT100003,Robert,Brown,Male,52,PA,Former,Medicare,171.5,NaN,...,False,False,False,False,False,False,False,False,True,False
4,PT100004,Priya,Rossi,Female,36,AZ,Never,Medicaid,169.7,65.0,...,False,True,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,PT101195,Elizabeth,Silva,Female,27,AZ,Never,Private,177.1,73.5,...,False,False,False,False,False,False,False,False,False,False
1196,PT101196,Joseph,Rodriguez,Female,32,NY,Never,Private,175.9,83.8,...,True,False,False,False,False,False,False,False,True,False
1197,PT101197,Patricia,White,Male,52,PA,Current,Private,171.0,66.0,...,False,False,True,False,False,False,False,False,False,False
1198,PT101198,John,Chen,Female,27,CA,Never,Medicare,175.2,NaN,...,False,False,False,False,False,False,False,False,False,True


In [15]:
## removing the first column---- working on multicolinearity

P_records_HE=pd.get_dummies(P_records, columns=['primary_condition', 'blood_type'], drop_first=True)
P_records_HE

,patient_id,first_name,last_name,gender,age,state,smoking_status,insurance_type,height_cm,weight_kg,...,primary_condition_Obesity,primary_condition_Osteoarthritis,primary_condition_Type 2 Diabetes,blood_type_A-,blood_type_AB+,blood_type_AB-,blood_type_B+,blood_type_B-,blood_type_O+,blood_type_O-
0,PT100000,Sarah,Jackson,Male,0,CA,Former,Private,152.3,81.8,...,False,False,True,False,False,False,False,False,True,False
1,PT100001,Jessica,Smith,Female,53,PA,Former,Medicaid,183.2,45.6,...,False,False,False,False,False,False,False,False,True,False
2,PT100002,John,Nguyen,Male,70,PA,Never,Private,178.1,66.5,...,False,False,False,False,False,False,False,False,False,False
3,PT100003,Robert,Brown,Male,52,PA,Former,Medicare,171.5,NaN,...,False,False,False,False,False,False,False,False,True,False
4,PT100004,Priya,Rossi,Female,36,AZ,Never,Medicaid,169.7,65.0,...,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,PT101195,Elizabeth,Silva,Female,27,AZ,Never,Private,177.1,73.5,...,False,False,False,False,False,False,False,False,False,False
1196,PT101196,Joseph,Rodriguez,Female,32,NY,Never,Private,175.9,83.8,...,False,True,False,False,False,False,False,False,True,False
1197,PT101197,Patricia,White,Male,52,PA,Current,Private,171.0,66.0,...,False,False,False,False,False,False,False,False,False,False
1198,PT101198,John,Chen,Female,27,CA,Never,Medicare,175.2,NaN,...,False,False,False,False,False,False,False,False,False,True


In [61]:
P_records['primary_condition'].value_counts()

primary_condition
Hypertension               153
Type 2 Diabetes            137
Obesity                    110
Depression                 109
Anxiety Disorder            79
Asthma                      79
Coronary Artery Disease     75
Osteoarthritis              54
Hypothyroidism              44
COPD                        41
Atrial Fibrillation         39
Chronic Kidney Disease      33
GERD                        24
Migraine                    20
Name: count, dtype: int64

In [25]:
P_records.isnull().sum()

patient_id              0
first_name              0
last_name               0
gender                  0
age                     0
blood_type             55
state                   0
smoking_status         52
insurance_type          0
primary_condition       5
height_cm              53
weight_kg              48
systolic_bp             0
diastolic_bp            0
heart_rate_bpm          0
last_admission_date     0
dtype: int64

In [27]:
P_records.dropna(inplace=True)

In [28]:
P_records.isnull().sum()

patient_id             0
first_name             0
last_name              0
gender                 0
age                    0
blood_type             0
state                  0
smoking_status         0
insurance_type         0
primary_condition      0
height_cm              0
weight_kg              0
systolic_bp            0
diastolic_bp           0
heart_rate_bpm         0
last_admission_date    0
dtype: int64

In [29]:
X=P_records[['primary_condition', 'blood_type', 'height_cm', 'weight_kg']]
X

,primary_condition,blood_type,height_cm,weight_kg
0,Type 2 Diabetes,O+,152.3,81.8
1,Anxiety Disorder,O+,183.2,45.6
2,Asthma,A+,178.1,66.5
4,Type 2 Diabetes,O+,169.7,65.0
5,Depression,O+,181.8,100.9
...,...,...,...,...
1193,Asthma,O+,168.0,70.2
1194,Coronary Artery Disease,O+,177.5,70.6
1196,Osteoarthritis,O+,175.9,83.8
1197,Chronic Kidney Disease,A+,171.0,66.0


In [30]:
Y=P_records['heart_rate_bpm']
Y

0        75
1        75
2        66
4        72
5        76
       ... 
1193     66
1194     87
1196    102
1197     66
1199     94
Name: heart_rate_bpm, Length: 997, dtype: int64

##**** applying One-Hot Encoding in Pandas--- has a limitation, it does not remember the order of columns

### applying One-Hot Encoding using sklearn class in ML

In [31]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2)

In [32]:
X_train

,primary_condition,blood_type,height_cm,weight_kg
1173,Hypertension,O-,178.7,93.6
821,Obesity,O-,174.6,66.1
1092,Anxiety Disorder,O+,161.6,68.2
175,Hypothyroidism,A+,178.0,59.6
1172,Osteoarthritis,A+,174.5,60.4
...,...,...,...,...
854,Asthma,B-,175.8,63.5
1114,Coronary Artery Disease,B-,167.0,84.4
306,Type 2 Diabetes,O+,165.4,68.9
1013,Migraine,A+,149.2,85.7


In [22]:
from sklearn.preprocessing import OneHotEncoder

In [49]:
OHE=OneHotEncoder(drop='first')

## drop='first'----- removes the first column from both test and train, sparse=False----  we do not need to convert to array, as by default its true

In [50]:
X_train_encoded=OHE.fit_transform(X_train[['primary_condition', 'blood_type']]).toarray()
X_train_encoded

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(797, 20))

In [51]:
X_test_encoded=OHE.fit_transform(X_test[['primary_condition', 'blood_type']]).toarray()
X_test_encoded

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.]], shape=(200, 20))

In [56]:
OHE=OneHotEncoder(drop='first', sparse_output=False, dtype=np.int32)  

### dtype=np.int32 converts the values from float to int

In [57]:
X_train_encoded=OHE.fit_transform(X_train[['primary_condition', 'blood_type']])
X_train_encoded

array([[0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(797, 20), dtype=int32)

In [58]:
X_test_encoded=OHE.fit_transform(X_test[['primary_condition', 'blood_type']])
X_test_encoded

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 1, 0]], shape=(200, 20), dtype=int32)

In [59]:
np.hstack((X_train[['height_cm', 'weight_kg']].values, X_train_encoded)).shape

(797, 22)

In [60]:
np.hstack((X_test[['height_cm', 'weight_kg']].values, X_test_encoded)).shape

(200, 22)

### Onehotencoding with top categories 

In [ ]:
##  with "primary condition"---- we will take the categories below 54 as others and rest will be individual, refer to following code

## P_records['primary_condition'].value_counts()

In [62]:
counts=P_records['primary_condition'].value_counts()

In [63]:
P_records['primary_condition'].nunique()
threshold=54

In [64]:
replc = counts[counts <= threshold].index

In [67]:
pd.get_dummies(P_records['primary_condition'].replace(replc, 'uncommon')).astype(int).sample(5)

,Anxiety Disorder,Asthma,Coronary Artery Disease,Depression,Hypertension,Obesity,Type 2 Diabetes,uncommon
789,0,0,0,0,0,1,0,0
852,0,0,0,0,0,0,0,1
402,0,0,0,0,0,0,1,0
1144,1,0,0,0,0,0,0,0
457,0,0,0,0,0,0,1,0


## Column Transformer

In [68]:
import pandas as pd
import seaborn as sns
import numpy as np

In [69]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [70]:
P_records.head(2)

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
0,PT100000,Sarah,Jackson,Male,0,O+,CA,Former,Private,Type 2 Diabetes,152.3,81.8,71,58,75,2024-07-19
1,PT100001,Jessica,Smith,Female,53,O+,PA,Former,Medicaid,Anxiety Disorder,183.2,45.6,114,89,75,2025-01-16


In [71]:
P_records.isnull().sum()

patient_id             0
first_name             0
last_name              0
gender                 0
age                    0
blood_type             0
state                  0
smoking_status         0
insurance_type         0
primary_condition      0
height_cm              0
weight_kg              0
systolic_bp            0
diastolic_bp           0
heart_rate_bpm         0
last_admission_date    0
dtype: int64

In [72]:
X=P_records[['primary_condition', 'smoking_status', 'blood_type', 'height_cm', 'systolic_bp']]
X

,primary_condition,smoking_status,blood_type,height_cm,systolic_bp
0,Type 2 Diabetes,Former,O+,152.3,71
1,Anxiety Disorder,Former,O+,183.2,114
2,Asthma,Never,A+,178.1,104
4,Type 2 Diabetes,Never,O+,169.7,117
5,Depression,Former,O+,181.8,115
...,...,...,...,...,...
1193,Asthma,Former,O+,168.0,115
1194,Coronary Artery Disease,Never,O+,177.5,117
1196,Osteoarthritis,Never,O+,175.9,146
1197,Chronic Kidney Disease,Current,A+,171.0,132


In [73]:
Y=P_records[['heart_rate_bpm']]
Y

,heart_rate_bpm
0,75
1,75
2,66
4,72
5,76
...,...
1193,66
1194,87
1196,102
1197,66


In [74]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test=train_test_split(X, Y, test_size=0.3)

In [76]:
X_train

,primary_condition,smoking_status,blood_type,height_cm,systolic_bp
559,Type 2 Diabetes,Never,A+,161.9,105
334,Type 2 Diabetes,Never,AB-,157.7,145
902,Type 2 Diabetes,Former,B+,174.2,115
897,Asthma,Never,A+,147.6,118
416,Osteoarthritis,Former,A+,158.6,116
...,...,...,...,...,...
62,Hypertension,Never,O-,156.1,135
421,Anxiety Disorder,Never,B-,161.4,120
1073,Anxiety Disorder,Never,A+,173.1,122
443,Asthma,Never,A+,145.9,128


In [77]:
from sklearn.compose import ColumnTransformer

In [79]:
CT=ColumnTransformer(transformers=[('tnf', OneHotEncoder(sparse_output=False, drop='first'), ['primary_condition', 'smoking_status', 'blood_type'])], remainder='passthrough')

In [80]:
CT.fit_transform(X_train)

array([[  0. ,   0. ,   0. , ...,   0. , 161.9, 105. ],
       [  0. ,   0. ,   0. , ...,   0. , 157.7, 145. ],
       [  0. ,   0. ,   0. , ...,   0. , 174.2, 115. ],
       ...,
       [  0. ,   0. ,   0. , ...,   0. , 173.1, 122. ],
       [  1. ,   0. ,   0. , ...,   0. , 145.9, 128. ],
       [  0. ,   0. ,   0. , ...,   0. , 178.4, 116. ]], shape=(697, 24))

In [82]:
CT.transform(X_test)

array([[  0. ,   0. ,   0. , ...,   1. , 183.3, 126. ],
       [  0. ,   0. ,   0. , ...,   0. , 172.7, 135. ],
       [  0. ,   0. ,   0. , ...,   0. , 166.7, 110. ],
       ...,
       [  0. ,   0. ,   0. , ...,   0. , 157.7, 130. ],
       [  0. ,   0. ,   0. , ...,   0. , 151.5, 120. ],
       [  0. ,   0. ,   0. , ...,   0. , 165.9,  98. ]], shape=(300, 24))

###  applying Column Transformer for both ordinal and nominal together

In [83]:
P_I=pd.read_csv('lab_results.csv')
P_I.head(2)

,lab_id,patient_id,test_name,result_value,reference_range_low,reference_range_high,flag,test_date,ordering_facility
0,LAB300000,PT101182,ALT (U/L),13.30,7.0,56.0,Normal,2024-09-20,Northside Clinic Lab
1,LAB300001,PT100847,Hemoglobin (g/dL),10.59,12.0,17.5,Low,2023-04-22,Northside Clinic Lab


In [86]:
P_I.isnull().sum()

lab_id                    0
patient_id                0
test_name                 0
result_value              0
reference_range_low       0
reference_range_high    400
flag                      0
test_date                 0
ordering_facility         0
dtype: int64

In [88]:
X=P_I[['test_name', 'reference_range_low', 'reference_range_high', 'flag', 'ordering_facility']]
X

,test_name,reference_range_low,reference_range_high,flag,ordering_facility
0,ALT (U/L),7.0,56.0,Normal,Northside Clinic Lab
1,Hemoglobin (g/dL),12.0,17.5,Low,Northside Clinic Lab
2,HDL Cholesterol (mg/dL),40.0,NaN,Normal,Quick Diagnostics
3,Hemoglobin A1c (%),4.0,5.7,Normal,Central Hospital Lab
4,Fasting Glucose (mg/dL),70.0,100.0,Normal,Quick Diagnostics
...,...,...,...,...,...
3995,Fasting Glucose (mg/dL),70.0,100.0,Normal,University Medical Lab
3996,HDL Cholesterol (mg/dL),40.0,NaN,Normal,University Medical Lab
3997,Hemoglobin A1c (%),4.0,5.7,Low,Central Hospital Lab
3998,Creatinine (mg/dL),0.6,1.3,High,Community Health Lab


In [90]:
Y=P_I[['result_value']]
Y

,result_value
0,13.30
1,10.59
2,60.77
3,5.18
4,87.17
...,...
3995,85.06
3996,57.46
3997,3.06
3998,1.35


In [89]:
P_I['flag'].unique()

<StringArray>
['Normal', 'Low', 'High']
Length: 3, dtype: str

In [99]:
CT_P_I=ColumnTransformer(transformers=[
    ('tnf1', OneHotEncoder(sparse_output=False, drop='first'), ['test_name', 'ordering_facility']), 
    ('tnf2', OrdinalEncoder(categories=[['Normal', 'Low', 'High']]), ['flag']),
    ('tnf3', SimpleImputer(), ['reference_range_high'])], remainder='passthrough')

In [100]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test=train_test_split(X, Y, test_size=0.3)

In [101]:
CT_P_I.fit_transform(X_train)

array([[  1. ,   0. ,   0. , ...,   1. ,   1.3,   0.6],
       [  0. ,   0. ,   0. , ...,   0. , 100. ,   0. ],
       [  0. ,   1. ,   0. , ...,   0. , 100. ,  70. ],
       ...,
       [  0. ,   0. ,   0. , ...,   2. ,   5.7,   4. ],
       [  0. ,   0. ,   0. , ...,   0. ,   4. ,   0.4],
       [  1. ,   0. ,   0. , ...,   0. ,   1.3,   0.6]], shape=(2800, 16))

In [102]:
CT_P_I.transform(X_test)

array([[  0. ,   0. ,   0. , ...,   0. ,   4. ,   0.4],
       [  0. ,   0. ,   0. , ...,   0. ,   5.7,   4. ],
       [  1. ,   0. ,   0. , ...,   0. ,   1.3,   0.6],
       ...,
       [  0. ,   0. ,   0. , ...,   0. ,   4. ,   0.4],
       [  1. ,   0. ,   0. , ...,   0. ,   1.3,   0.6],
       [  0. ,   1. ,   0. , ...,   0. , 100. ,  70. ]], shape=(1200, 16))